name: CI-MLFlow-Retrain

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        channels: conda-forge, defaults 
        channel-priority: strict
        auto-activate-base: false
        # File conda.yaml Anda akan digunakan untuk membuat env
        environment-file: MLProject/conda.yaml 
        activate-environment: metaverse_env 

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run . -e main

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: retrained-model
        path: MLProject/mlruns/

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build MLflow Docker Image
      shell: bash -l {0} 
      run: |
        cd MLProject
        LATEST_RUN_DIR=$(ls -t mlruns/0/ | head -n 1)
        MODEL_PATH="mlruns/0/$LATEST_RUN_DIR/artifacts/model"
        echo "Building Docker image from model at $MODEL_PATH"
        mlflow models build-docker -m $MODEL_PATH -n metaverse_model:latest

    - name: Push Docker Image
      run: |
        docker tag metaverse_model:latest ${{ secrets.DOCKER_USERNAME }}/metaverse_model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/metaverse_model:latest